language: php

matrix:
  include:
    - php : 7.2
    - php : 7.3
  fast_finish: true

services:
  - mysql

env:
  global:
    TEST_CONFIG="phpunit.xml.dist"

before_script:
  - travis_retry
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install --no-interaction --prefer-source
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:drop --env=test --force
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n

script:
  - vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run src/
  - vendor/bin/phpmd src/ text custom-phpmd-ruleset
  - vendor/bin/phpcpd src/

notifications:
  email:
    -  mailer.dev.brice@gmail.com