language: php


matrix:
  include:
    - php : 7.0
    - php : 7.1
  fast_finish: true

env:
  global:
    TEST_CONFIG="phpunit.xml.dist"

before_script:
  - travis_retry
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - then vendor/phpunit/phpunit/phpunit --configuration $TEST_CONFIG
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run src/
  - vendor/bin/phpmd src/ text codesize,unusedcode,naming

install: travis_retry composer install --no-interaction --prefer-source