liv_app:
    resource: "@LIVAppBundle/Resources/config/routing.yml"
    prefix:   /

liv_user:
    resource: "@LIVUserBundle/Resources/config/routing.yml"
    prefix:   /user

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
