liv_app_homepage:
    path:     /
    defaults: { _controller: LIVAppBundle:Default:index }

liv_place:
    resource: "@LIVAppBundle/Resources/config/routing-place.yml"

liv_place_category:
    resource: "@LIVAppBundle/Resources/config/routing-place-category.yml"

