liv_app_homepage:
    path:     /
    defaults: { _controller: LIVAppBundle:Default:index }

liv_app_contact:
    path:   /contact
    defaults: { _controller: LIVAppBundle:Contact:contact}

liv_app_qui_sommes_nous:
    path: /about-livlyon
    defaults: { _controller: LIVAppBundle:Default:quiSommesNous}

liv_place:
    resource: "@LIVAppBundle/Resources/config/routing-place.yml"

liv_event:
    resource: "@LIVAppBundle/Resources/config/routing-event.yml"

liv_place_category:
    resource: "@LIVAppBundle/Resources/config/routing-place-category.yml"

liv_event_category:
    resource: "@LIVAppBundle/Resources/config/routing-event-category.yml"

liv_tag:
    resource: "@LIVAppBundle/Resources/config/routing-tag.yml"
